naver:
  client:
    id: 38ozWL7Gu4nAlCvOjX9d
    secret: N_7P220zde
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json

google:
  api:
    key: AIzaSyBRG5kqYuOMH88LAlI7HVWbcCglopIrTGc

kakao:
  map:
    appkey: 2e886fa0387a4683a275ed630512bc1f

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 15ffbbe2ef214a4f4a5bcf38219d6f08
          google:
            client-secret: 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
          naver:
            client-secret: 8jHaZCFbq4

  mail:
    password: foabrdxhkflaombo

custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUser:
              oauthId: oauthId
              nickname: nickname


